### ISSUE TITLE
Slide direction is messed up

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#174]
When Lara slides, her orientation chaotically changes, but mostly she end up in opposite direction to slide direction.

**Comment by vvs-** [comment]
It's not fixed. Try to slide in *Colosseum* for example.

**Comment by vvs-** [comment]
The sliding in *The Great Wall* doesn't work at all anymore.

**Comment by vvs-** [comment]
Also, it doesn't work in *Jungle*. I see two blended Lara models looking in opposite directions trying to slide simultaneously.

**Comment by vvs-** [comment]
No, actually it doesn't fix neither.

**Comment by stohrendorf** [comment]
Yep, famous last words, as I said :(

**Comment by vvs-** [comment]
It's a collision bug related to #182. Lara is pushed back and orientation is changed as it should when she stumbled on an impassable slope.

**Comment by vvs-** [comment]
May be the angle of a slope is messed up again somewhere.

**Comment by vvs-** [comment]
Also, try to step on a slope. It works incorrectly.

**Comment by vvs-** [comment]
Also, when Lara jumps using slopes her orientation now changed randomly because of this bug.

**Comment by vvs-** [comment]
Removing ghost objects partially fixed this too. Lara can slide now but orientation is still wrong.

**Comment by vvs-** [comment]
When Lara steps on a slope she now always turns 180 degrees. It doesn't matter what orientation she had before.

**Comment by Lwmte** [comment]
Now it's better, but one more thing that is incorrect.

Try to launch WALL.TR2. Lara should slide three times and in the end face the cave opening. But she does last slide wrong. This bug wasn't present before refactoring.

**Comment by vvs-** [comment]
Bullet 2.82 has horrible bugs, e.g.:
```
#define SIMD_PI           btScalar(3.1415926535897932384626433832795029)
#define SIMD_2_PI         btScalar(2.0) * SIMD_PI
#define SIMD_HALF_PI      (SIMD_PI * btScalar(0.5))
#define SIMD_RADS_PER_DEG (SIMD_2_PI / btScalar(360.0))
#define SIMD_DEGS_PER_RAD  (btScalar(360.0) / SIMD_2_PI)
```
That means that conversion from radians to degrees is horribly broken.

**Comment by vvs-** [comment]
It's fixed in Bullet 2.83. That's a direct result of switching from in-tree Bullet to system library.

**Comment by stohrendorf** [comment]
:frowning:

**Comment by vvs-** [comment]
It seems fixed now. Could it be closed?

**Comment by Lwmte** [comment]
But I have Bullet 2.83, and still this bug exists.

**Comment by vvs-** [comment]
I can't reproduce it on any level. Everything works just as it should.

**Comment by vvs-** [comment]
I'm using Bullet bulletphysics/bullet@1fa4819afc806cd8a7081cd48943fc9d0c25bb92

**Comment by stohrendorf** [comment]
@vvs- seems to have a bug free version running! Joke aside, I think somewhere is a tiny memory corruption that rarely manifests. But it could also be fixed with 89a3b63fcb00b1523044e359456d8dc281fc6bb2.

**Comment by vvs-** [comment]
Or it could be a problem with optimization. We already had such issues before.

**Comment by stohrendorf** [comment]
BTW, that's why I use `constexpr` and `enum class` wherever possible in my code (not in OpenTomb yet), and I think it would be good to `#undef` OpenTomb at some time.

**Comment by vvs-** [comment]
Please, reopen this if you still have this issue.

**Comment by Lwmte** [comment]
Yes, it still exists. Do you need a video demonstrating the bug?

**Comment by vvs-** [comment]
Yes, it would be helpful.

**Comment by vvs-** [comment]
After testing the engine with different compiler optimization levels I came to a conclusion that anything higher than `-O0` produced buggy code.

**Comment by stohrendorf** [comment]
Running OpenTomb with valgrind in `RelWithDebInfo` showed some interesting behaviour:
1. When jumping up, the first animation is played *twice*.
2. When landing, the animation stops, but Lara keeps on sliding, until this happens (without Lara being killed):
![slide-anim-bug](https://cloud.githubusercontent.com/assets/7853507/8895911/17be5b6e-33eb-11e5-88ef-3b775fefda9e.png)

**Comment by vvs-** [comment]
Exactly. All optimization bugs seems to be related to collisions.

**Comment by stohrendorf** [comment]
Seems like `Res_GenRoomCollision` is broken.

**Comment by Lwmte** [comment]
Collision bugs is a well-known issue, it was tested by TeslaRus and he said that all optimization levels above -O2 produce completely unworkable code (funny thing that he recently said to me he was able to produce stable build with MinGW-64 and -O3).

Seems that 'any' optimization in Bullet is generating buggy code. But we really don't know yet if it's Bullet or OpenTomb itself which is buggy.

**Comment by Lwmte** [comment]
Here is what happens: http://youtu.be/d33oCh2hFIM

Actually, when I recorded this video, something even more weird happened, as Lara stucked at sector border, and moreover, game crashed when I entered noclip mode (it happened at the end of the video, when Fraps obviously stopped capturing, since app crashed).

**Comment by stohrendorf** [comment]
Did it crash with 322110f4af8c8c6488436839378f7b6cec3c0fc6 or later? Because I have added a simple destruction check in `EngineContainer` there that throws an uncatched `std::runtime_error` if it detects that the container was destroyed (which isn't necessarily always detected due to the nature of bools).

**Comment by vvs-** [comment]
Some collision bugs were fixed recently. Is this issue still reproducible?

**Comment by Lwmte** [comment]
Yes, I still get the same issue.

**Comment by stohrendorf** [comment]
Exactly at 2:07, he says that the collision simulation will be less stable if you don't use margins.

**Comment by Lwmte** [comment]
I still get a bug, even with margins.

Also I finally was able to capture the bug on video! Look here: http://youtu.be/hMP9rXnbot4

It proves that it doesn't depend on 60 FPS lock, but indeed with active recording (i.e. 60 FPS lock) it occurs much more rarely, mostly it works as it should in such case. So it looks like some game frames are resetting some values they shouldn't, hence the occasional nature of this bug.

**Comment by stltomb** [comment]
Can you try it again with 840e83331bc4c3c0574ae8f78f2dc0846bda8476 applied? I can't reproduce this now.

**Comment by Lwmte** [comment]
No, unfortunately, bug still exists... I did a clean release build, and still the same.
By the way, sorry about that error with ghost objects. I was a bit lost among new code back then! :smile:

**Comment by stltomb** [comment]
Can't get it to reproduce, I tried compiling it with gcc and clang, with Debug and RelWithDebInfo and still nothing. However, if I let her slide backward, she starts facing forward on the next slope (TR2 Wall). Is this how it should work? The same thing happens on the build from before the refactoring.

**Comment by stohrendorf** [comment]
From looking at the code, I'd say that when sliding down backwards, the animation for sliding down with Lara's back first is rotated by 180 degrees (see character_controller.cpp:995). What needs to be done is to rotate her again by 180 degrees when she stops sliding.

**Comment by Gh0stblade** [comment]
If you roll onto a slope, it also messes up the slide direction.

**Comment by Lwmte** [comment]
Currently, almost everything messes up slide direction and/or animation, because sliding checks and calculations are done *outside* state control module. It means that Lara animates slide and actually slides in two different parts of the code.

It should be fixed by adding slide animation switches to the proper state functions. However, it won't fix slide direction.
