### ISSUE TITLE
LuaState submodule fails to build

### ISSUE THREAD

**Issue by vloup** [opentomb/OpenTomb#264]
So I'm unable to compile OpenTomb due to last LuaState commit.
I have to `git checkout HEAD~1` in the LuaState submodule to make it compile.

Log of my last clean compilation: https://gist.github.com/vloup/3f87dd60635422079c39 (not the last commit though, but it does not matter)

For the curious, here is my automatic build script: https://gist.github.com/vloup/a3b5bd93182e2b6d871d

**Comment by vvs-** [comment]
You shouldn't compile LuaState at all - only its' headers are needed by OpenTomb, there is no runtime library.

**Comment by Gh0stblade** [comment]
I can build OpenTomb just fine here.

**Comment by vvs-** [comment]
That's probably because you didn't update your submodules. The last commit in LuaState broke it.

**Comment by Gh0stblade** [comment]
Oh yeah I mis-read.

**Comment by stohrendorf** [comment]
In `resource.cpp:53`, change `uint16_t flg` to `int flg`, and tell me if it works.

**Comment by vvs-** [comment]
No, it doesn't. There is redefinition of `lua::stack::check` in `LuaState.h`.

**Comment by vloup** [comment]
Thanks for this quick reaction, I was not expecting such activity!
As vvs- said, it does not improve anything
build log: https://gist.github.com/vloup/1f98b7581f991c0f47ad

**Comment by stohrendorf** [comment]
Could be solved in 12bd89e. There were problems on 32-bit machines, where `lua::Integer` was a typedef for `int`.

**Comment by vvs-** [comment]
Nope, still doesn't work. Now it's `lua::stack::get` get redefined.

**Comment by vloup** [comment]
This sadly does not solve my issue. It seems there are other static assert failing somehow.
I'm on x86_64 and do compile for 64bit x86, so I doubt it is a 32bit issue.

build log: https://gist.github.com/vloup/c3dab0c6da2d7e4af313

**Comment by stohrendorf** [comment]
I have updated (again) the LuaState repo, seems that there was missing support for `long long` types.

**Comment by vloup** [comment]
It still fails to compile :(
https://gist.github.com/vloup/1b14a4c4663a24162f1d

**Comment by vvs-** [comment]
Now it's `lua::stack::read`.

**Comment by stohrendorf** [comment]
Another update. Hopefully this is solved now.

**Comment by vvs-** [comment]
It builds now but has a stack overflow at runtime:
```
Program received signal SIGSEGV, Segmentation fault.
0x08258370 in lua::stack::check<int> (luaState=0x84ce068, index=4)
    at 3rdparty/LuaState/include/./LuaStack.h:225
225	        return check<lua::Integer>(luaState, index);
```

**Comment by stohrendorf** [comment]
Updated LuaState.

**Comment by vloup** [comment]
It does still fail to compile on a static assert on my side. Am I missing anything?
https://gist.github.com/vloup/3e57f8fd80d3cfddf69d

**Comment by stohrendorf** [comment]
Updated LuaState. `ptrdiff_t` seems to have changed from `long` to `long long`, which wasn't supported by LuaState.

**Comment by vloup** [comment]
Nailed it!
It compiles and runs fine on my side, I hope vvs- is able to confirm.

Thanks a lot!
PS: I'm gonna delete all those gists when you close this issue.

**Comment by vvs-** [comment]
Yes, everything works now.
